name: flutter_clean_architecture
description: "A güil Mobility Ventures Project created by güil Mobility Ventures."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
